<?php

return [
    'new_appointment' => 'New Appointment',
    'create_appointment' => 'Create Appointment',
    'update_appointment' => 'Update Appointment',
    'all_calendars' => 'All Calendars',
    'space_available' => 'Space Available',
    'spaces_available' => 'Spaces Available',
    'add_timeslots' => 'Add Timeslots',
    'time_error' => 'The \"End Time\" needs to be later than the \"Start Time\".',
    'bulk_add_confirm' => 'Are you sure you want to add those bulk time slots?',
    'all_fields_required' => 'All fields are required.',
    'single_add_confirm' => 'You are about to add the following time slot(s)',
    'to' => 'to',
    'please_wait' => 'Please wait ...',
    'all_day' => 'All day',
    'change_date' => 'Change Date',
    'choose_customer' => 'Please choose a customer.',
    'fill_out_required_fields' => 'Please fill out all required fields.',
    'confirm_ts_delete' => 'Are you sure you want to delete this time slot?',
    'confirm_cts_delete' => 'Are you sure you want to delete this custom time slot?',
    'confirm_appt_delete' => 'Are you sure you want to cancel this appointment?',
    'clear_timeslots_confirm' => 'Are you sure you want to delete all of the timeslots for this day?',
    'appt_required_fields' => 'A name, email address and password are required.',
    'appt_required_guest_fields' => 'A name is required.',
    'appt_required_guest_fields_surname' => 'A first and last name are required.',
    'appt_required_guest_fields_all' => 'A first name, last name and email address are required.',
    'appt_required_guest_fields_name_email' => 'A name and an email address are required.',
    'confirm_appt_approve' => 'Are you sure you want to approve this appointment?',
    'confirm_appt_approve_all' => 'Are you sure you want to approve ALL pending appointments?',
    'confirm_appt_delete_all' => 'Are you sure you want to delete ALL pending appointments?',
    'confirm_appt_delete_past' => 'Are you sure you want to delete all PASSED pending appointments?',
];
