<?php

return [
    'account_successfully_updated' => 'Account Successfully Updated',
    'addInviteError' => 'You need to create a ticket before you can invite an attendee.',
    'attendees_required' => 'Please select at least one attendee',
    'attendee_already_cancelled' => 'Attendee Already Cancelled',
    'attendee_already_checked_in' => 'Attendee already checked in at :time ',
    'attendee_exception' => 'An error occurred while inviting this attendee. Please try again.',
    'attendee_successfully_checked_in' => 'Attendee Successfully Checked In',
    'attendee_successfully_checked_out' => 'Attendee Successfully Checked Out',
    'attendee_successfully_invited' => 'Attendee Successfully Invited!',
    'cant_delete_ticket_when_sold' => 'Sorry, you can\'t delete this ticket as some have already been sold',
    'check_in_all_tickets' => 'Check in all tickets associated to this order',
    'confirmation_malformed' => 'Your email has already been confirmed.',
    'confirmation_successful' => 'Success! Your email is now verified. You can now login.',
    'error' => [
        'email' => [
            'email' => 'Please enter a valid E-mail address.',
            'required' => 'E-mail address is required.',
            'unique' => 'E-mail already in use for this account.',
        ],
        'first_name' => [
            'required' => 'Please enter your first name.',
        ],
        'last_name' => [
            'required' => 'Please enter your last name.',
        ],
        'page_bg_color' => [
            'required' => 'Please enter a background color.',
        ],
        'page_header_bg_color' => [
            'required' => 'Please enter a header background color.',
        ],
        'password' => [
            'passcheck' => 'This password is incorrect.',
        ],
    ],
    'event_create_exception' => 'Whoops! There was a problem creating your event. Please try again.',
    'event_page_successfully_updated' => 'Event Page Successfully Updated.',
    'event_successfully_updated' => 'Event Settings Successfully Updated!',
    'fill_email_and_password' => 'Please fill in your email and password',
    'image_upload_error' => 'There was a problem uploading your image.',
    'incorrect_captcha' => 'Robot verification failed, please try again.',
    'invalid_ticket_error' => '"Invalid Ticket! Please try again."',
    'login_password_incorrect' => 'Your username/password combination was incorrect',
    'marketing_updated_message' => 'Success! Tracking pixels have been updated.',
    'maximum_refund_amount' => 'The maximum amount you can refund is :money',
    'message_successfully_sent' => 'Message Successfully Sent!',
    'new_order_received' => ' New order received for :event [:order]',
    'nothing_to_do' => 'Nothing to do',
    'nothing_to_refund' => 'Nothing to refund.',
    'no_organiser_name_error' => 'You must give a name for the event organizer.',
    'num_attendees_checked_in' => ':num Attendee(s) Checked in.',
    'order_already_refunded' => 'Order has already been refunded!',
    'order_cant_be_refunded' => 'Order Can\'t Be Refunded!',
    'order_page_successfully_updated' => 'Order Page Successfully Updated.',
    'order_payment_status_successfully_updated' => 'Order Payment Status Successfully Updated',
    'organiser_design_successfully_updated' => 'Organizer Design Successfully Updated!',
    'organiser_other_error' => 'There was an issue finding the organizer.',
    'password_successfully_reset' => 'Password Successfully Reset!',
    'payment_information_successfully_updated' => 'Payment Information Successfully Updated',
    'please_enter_a_background_color' => 'Please enter the background color.',
    'quantity_min_error' => 'Quantity available can\'t be less the amount sold or reserved.',
    'refreshing' => 'Refreshing...',
    'refund_exception' => 'There has been a problem processing your refund. Please check your information and try again.',
    'refund_only_numbers_error' => 'Only numbers are allowed in this field.',
    'social_settings_successfully_updated' => 'Social Settings have been successfully updated!',
    'sort' => [
        'created_at' => 'Creation Date',
        'event_title' => 'Event Title',
        'quantity_sold' => 'Quantity Sold',
        'sales_volume' => 'Sales Volume',
        'sort_order' => 'Custom Sort Order',
        'start_date' => 'Start Date',
        'title' => 'Ticket Title',
    ],
    'stripe_error' => 'There was an error connecting your Stripe account. Please try again.',
    'stripe_success' => 'You have successfully connected your Stripe account.',
    'successfully_cancelled_attendee' => 'Successfully Cancelled Attendee!',
    'successfully_undone_attendee' => 'Attendee Cancelation Successfully Undone',
    'successfully_cancelled_attendees' => 'Successfully Cancelled Attendees!',
    'successfully_created_organiser' => 'Successfully Created Organizer!',
    'successfully_created_question' => 'Successfully Created Question',
    'successfully_deleted_question' => 'Successfully Deleted Question',
    'successfully_edited_question' => 'Successfully Edited Question',
    'successfully_refunded_and_cancelled' => 'Order Successfully Refunded',
    'successfully_refunded_order' => 'Successfully Refunded Order!',
    'successfully_saved_details' => 'Successfully Saved Details!',
    'successfully_updated_attendee' => 'Successfully Updated Attendee!',
    'successfully_updated_organiser' => 'Successfully Updated Organizer!',
    'successfully_updated_question' => 'Question Successfully Updated',
    'successfully_updated_question_order' => 'Question Order Successfully Updated',
    'success_name_has_received_instruction' => 'Success! <b>:name</b> has been sent further instructions.',
    'survey_answers' => 'Survey Answers',
    'the_order_has_been_updated' => 'The Order Has Been Updated',
    'this_question_cant_be_deleted' => 'This Question Can\'t Be Deleted',
    'tickets_for_event' => 'Your tickets for :event.',
    'ticket_field_required_error' => 'The ticket field is required. ',
    'ticket_not_exists_error' => 'The ticket you have selected does not exist',
    'ticket_order_successfully_updated' => 'Ticket Order Successfully Updated',
    'ticket_successfully_deleted' => 'Ticket Successfully Deleted',
    'ticket_successfully_resent' => 'Ticket Successfully Resent!',
    'ticket_successfully_updated' => 'Ticket Successfully Updated!',
    'whoops' => 'Whoops! Looks like something went wrong. Please try again.',
    'your_password_reset_link' => 'Your Password Reset Link',
];
