<?php

return [
    'account_settings' => 'Account Settings',
    'additional_organiser_options' => 'Additional Organizer Options',
    'background_color' => 'Background Color',
    'continue_to' => 'Continue to',
    'create_an_organiser' => 'Create An Organizer',
    'create_new_organiser' => 'Create New Organizer',
    'create_organiser' => 'Create Organizer',
    'create_organiser_text' => 'Before you create events you\'ll need to create an organizer. An organizer is simply whoever is organizing the event. It can be anyone, from a person to an organization.',
    'current_logo' => 'Current Logo',
    'customize' => 'Customize',
    'dashboard' => 'Dashboard',
    'delete_logo?' => 'Delete Logo?',
    'enable_public_organiser_page' => 'Enable Public Organizer Page',
    'event' => 'Event',
    'events' => 'My events',
    'event_calendar' => 'Event Calendar',
    'facebook_pixel_id' => 'Facebook pixel ID',
    'facebook_pixel_id_placeholder' => 'Facebook pixel ID',
    'google_ads_code' => 'Google Ads Pixel Id',
    'google_ads_event_label' => 'Event snippet label',
    'google_ads_event_label_placeholder' => 'Event snippet label',
    'google_ads_id_placeholder' => 'AW-XXXXXXXX',
    'google_analytics_code' => 'Google Analytics Code',
    'google_analytics_code_placeholder' => 'G-XXXXX',
    'google_tag_manager_code' => 'Google Tag Manager Code',
    'google_tag_manager_code_placeholder' => 'GTM-XXXXX',
    'header_background_color' => 'Header Background Color',
    'hide_additional_organiser_options' => 'Hide Additional Organizer Options',
    'make_organiser_hidden' => 'Hide organizer page from the public.',
    'make_organiser_public' => 'Make organizer page visible to the public.',
    'my_account' => 'My Account',
    'no' => 'No',
    'no_upcoming_events' => 'You have no events coming up.',
    'no_upcoming_events_click' => 'You can click here to create an event.',
    'or' => 'or',
    'organiser_description' => 'Organizer Description',
    'organiser_description_placeholder' => '',
    'organiser_design' => 'Organizer Design',
    'organiser_details' => 'Organizer Details',
    'organiser_email' => 'Organizer Email',
    'organiser_email_placeholder' => '',
    'organiser_events' => 'Organizer Events',
    'organiser_facebook' => 'Organizer Facebook',
    'organiser_facebook_placeholder' => 'E.g http://www.facebook.com/MyFaceBookPage',
    'organiser_logo' => 'Organizer Logo',
    'organiser_logo_help' => 'We recommend a square image, as this will look best on printed tickets and event pages.',
    'organiser_menu' => 'Organizer',
    'organiser_name' => 'Organizer Name',
    'organiser_name_dashboard' => ':name Dashboard',
    'organiser_name_events' => ':name Events',
    'organiser_name_placeholder' => 'Who\'s organising the event?',
    'organiser_page' => 'Organizer Page',
    'organiser_page_design' => 'Organizer Page Design',
    'organiser_page_preview' => 'Organizer Page Preview',
    'organiser_page_visibility_text' => 'Organizer pages contain a public list of past and upcoming events.',
    'organiser_settings' => 'Organizer Settings',
    'organiser_tax_id' => 'Tax ID',
    'organiser_tax_name' => 'Tax Name',
    'organiser_tax_prompt' => 'Do you want to charge taxes?',
    'organiser_tax_value' => 'Tax Value',
    'organiser_tax_rate' => 'Tax Rate',
    'organiser_twitter' => 'Organizer Twitter',
    'organiser_twitter_placeholder' => 'E.g http://www.twitter.com/MyTwitterPage',
    'organiser_username_facebook_placeholder' => 'MyFacebookPage',
    'organiser_username_twitter_placeholder' => 'MyTwitterPage',
    'or_caps' => 'OR',
    'sales_volume' => 'Sales Volume',
    'save_organiser' => 'Save Organizer',
    'search_placeholder' => 'Search Events..',
    'select_an_organiser' => 'Select An Organizer',
    'select_organiser' => 'Select Organizer',
    'text_color' => 'Text Color',
    'tickets_sold' => 'Tickets Sold',
    'tiktok_pixel_id' => 'Tiktok pixel ID',
    'tiktok_pixel_id_placeholder' => 'Tiktok pixel ID',
    'yes' => 'Yes',
    'charge_fees' => 'Charge Fees?',
    'include_merchant_fee' => 'Include Merchant Fee',
    'include_ticketscandy_service_fee' => 'Pass TicketsCandy Service Fee',

    'pass_merchant_fee' => 'Pass Merchant Fee',
    'pass_merchant_fee_description' => 'Include merchant fees in ticket price so customers can cover the expense.',
    'pass_ticketscandy_service_fees' => 'Pass TicketsCandy Service Fee',
    'pass_ticketscandy_service_fees_description' => 'Include TicketsCandy fees in ticket price so customers can cover the expense.',
    'additional_fees' => 'Additional Fees',
    'additional_fees_description' => 'If you would like to charge any additional fees you can set them up here.',
    'additional_fee_percentage' => 'Additional Fee Percentage',
    'additional_fee_fixed_price' => 'Additional Fee Fixed Price',

    'customer_appointment_reminder_description' => 'Send a reminder email to the customer 24 hours before their appointment.',
    'new_order_notification' => 'New Order Notification',
    'new_order_notification_description' => 'Send a notification to the admin when a new order is placed.',

    'website_widget' => 'Website Widget',
    'ticketing_widget_code' => 'Ticketing Widget Code',
    'tracking_id' => 'Tracking ID',
    'measurement_id' => 'Measurement ID',
    'pixel_id' => 'Pixel ID',

    'charge_fees_description' => 'These are optional fees you can include in the cost of each ticket.',


];
