<?php

return [
    'after_welcome' => 'Before you continue please update your account with your name and a new password.',
    'already_have_account' => 'Already have account? <a class="semibold" href=":url">Sign In</a>',
    'change_password' => 'Change Password',
    'confirm_new_password' => 'Confirm New Password',
    'dont_have_account_button' => 'Don\'t have an account? <a class="semibold" href=":url">Sign up</a>',
    'email' => 'Email',
    'first_name' => 'First Name',
    'forgot_password' => 'Forgot Password',
    'forgot_password?' => 'Forgot Password?',
    'hide_change_password' => 'Hide Change Password',
    'last_name' => 'Last Name',
    'login' => 'Log in',
    'login_fail_msg' => 'Please check your details and try again.',
    'my_account' => 'My Account',
    'my_profile' => 'My Profile',
    'new_password' => 'New Password',
    'old_password' => 'Old Password',
    'password' => 'Password',
    'password_again' => 'Password again',
    'password_already_sent' => 'The password reset instructions have been sent to your email.',
    'reset_input_errors' => 'There were some problems with your input.',
    'reset_password' => 'Reset Password',
    'reset_password_success' => 'The password reset instructions have been sent to your email.',
    'sign_up' => 'Sign Up',
    'sign_up_first_run' => 'You\'re almost there. Just create a user account and you\'re ready to go.',
    'terms_and_conditions' => '&nbsp;&nbsp;I agree to <a target="_blank" href=":url"> Terms & Conditions </a>',
    'welcome_to_app' => 'Welcome to :app!',
    'your_email' => 'Your Email',
    'role' => 'Role',
    'create_an_account' => 'Create an account',
    'add_user' => 'Add User',
    'add_user_role_description' => 'Admin role has access to the entire dashboard (events, orders, tools, etc.). Manager role only has access to appointments calendar and attendees list.',
];
